// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZSCreatorPlatform.Web.Admin.Domain;

namespace ZSCreatorPlatform.Web.Admin.Migrations
{
    [DbContext(typeof(ZSCreatroDbContext))]
    [Migration("20230224024446_init022410")]
    partial class init022410
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ZSCreatorPlatform.Web.Admin.Domain.Models.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasComment("主键id");

                    b.Property<string>("Address")
                        .HasColumnName("Address")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasComment("分店地址")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasComment("分店名称")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("T_Store");

                    b.HasComment("分店表");
                });

            modelBuilder.Entity("ZSCreatorPlatform.Web.Admin.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("主键Id");

                    b.Property<string>("Address")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasComment("用户地址")
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasComment("用户创建时间");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasComment("用户名称")
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasComment("用户密码")
                        .HasMaxLength(100);

                    b.Property<int>("StoreId")
                        .HasColumnName("StoreId")
                        .HasColumnType("int")
                        .HasComment("所属分店id");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime(6)")
                        .HasComment("用户最后修改时间");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("T_User");

                    b.HasComment("用户表");
                });

            modelBuilder.Entity("ZSCreatorPlatform.Web.Admin.Domain.Models.User", b =>
                {
                    b.HasOne("ZSCreatorPlatform.Web.Admin.Domain.Models.Store", "Store")
                        .WithMany("Users")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
